# Generated by Django 5.0.6 on 2024-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor/default.jpeg', null=True, upload_to='doctor'),
        ),
    ]
